pull_request_rules:
  - name: label scala-steward's PRs
    conditions:
      - author=scala-steward-bot-kailuowang[bot] 
    actions:
      label:
        add: [dependencies]
  - name: automatically merge scala-steward's patch PRs
    conditions:
      - author=scala-steward-bot-kailuowang[bot]
      - status-success=Build and Test (ubuntu-latest, 2.12.16, adopt@1.8)
    actions:
      merge:
        method: merge
